version: 2

seeds:
  - name: raw_customers
    description: A list of customers
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: first_name
        tests:
          - not_null